#!/usr/bin/env ruby

require './lib/Syachihoko.rb'

syc = Syachihoko.new

cmd = ARGV[0]
case cmd
when "collect"
  filename = ARGV[1]
  syc.collect(filename).each{|a|
      puts "#{a[0]}:#{a[1]}"
  }
else
  puts "command not found!!!!"
end



