#!/usr/bin/env ruby

require './lib/Syachihoko.rb'

WEBAPP_PATH='/home/isucon/webapp'

syc = Syachihoko.new

cmd = ARGV[0]
case cmd
when "collect"
  filename = ARGV[1]
  i = 0
  syc.collect(filename).each{|a|
      i += 1
    puts "#{i}:#{a[0]}:#{a[1]}"
  }
when "pull"
  change_dir = "cd #{WEBAPP_PATH}"
  system(change_dir)
  git_pull = "git pull origin master"
  system(git_pull)
when "push"
  change_dir = "cd #{WEBAPP_PATH}"
  system(change_dir)
  git_push = "git push origin master"
  system(git_push)
when "bench"
  bench = "isucon3 benchmark"
  system(bench)
when "kill"
  process_name = ARGV[1]
  kill_process = "kill `ps -ef | grep #{process_name} | awk '{print $2;}'`"
  system(kill_process)
else
  puts "command not found!!!!"
end



